-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 13:34:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Infofilms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Infofilms` (
  `idfilm` INT(10) NOT NULL AUTO_INCREMENT,
  `titrefilm` VARCHAR(45) NOT NULL,
  `datesortie` DATE NOT NULL,
  `duree` VARCHAR(45) NOT NULL,
  `realisateur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfilm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoriefilms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoriefilms` (
  `idcat` INT(10) NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NOT NULL,
  `comedie` VARCHAR(45) NOT NULL,
  `aventure` VARCHAR(45) NOT NULL,
  `drame` VARCHAR(45) NOT NULL,
  `horreur` VARCHAR(45) NOT NULL,
  `Infofilms_codefilm` INT(10) NOT NULL,
  PRIMARY KEY (`idcat`),
  INDEX `fk_categoriefilms_Infofilms_idx` (`Infofilms_codefilm` ASC) VISIBLE,
  CONSTRAINT `fk_categoriefilms_Infofilms`
    FOREIGN KEY (`Infofilms_codefilm`)
    REFERENCES `mydb`.`Infofilms` (`idfilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paiement` (
  `idpaiement` INT(10) NOT NULL AUTO_INCREMENT,
  `datepaiement` DATE NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `montant` FLOAT NOT NULL,
  PRIMARY KEY (`idpaiement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `idClients` INT NOT NULL AUTO_INCREMENT,
  ` Noms` VARCHAR(45) NOT NULL,
  `Prenoms` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(30) NOT NULL,
  `categoriefilms_codecat` INT(10) NOT NULL,
  `paiement_codepaiement` INT(10) NOT NULL,
  PRIMARY KEY (`idClients`, ` Noms`, `Prenoms`, `Email`),
  INDEX `fk_Clients_categoriefilms1_idx` (`categoriefilms_codecat` ASC) VISIBLE,
  INDEX `fk_Clients_paiement1_idx` (`paiement_codepaiement` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_categoriefilms1`
    FOREIGN KEY (`categoriefilms_codecat`)
    REFERENCES `mydb`.`categoriefilms` (`idcat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_paiement1`
    FOREIGN KEY (`paiement_codepaiement`)
    REFERENCES `mydb`.`paiement` (`idpaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`louer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`louer` (
  `idlouer` INT(10) NOT NULL AUTO_INCREMENT,
  `date_location` DATE NOT NULL,
  `date_retour` DATETIME NOT NULL,
  `Clients_idClients` INT NOT NULL,
  `Infofilms_codefilm` INT(10) NOT NULL,
  PRIMARY KEY (`idlouer`),
  INDEX `fk_louer_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  INDEX `fk_louer_Infofilms1_idx` (`Infofilms_codefilm` ASC) VISIBLE,
  CONSTRAINT `fk_louer_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `mydb`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_louer_Infofilms1`
    FOREIGN KEY (`Infofilms_codefilm`)
    REFERENCES `mydb`.`Infofilms` (`idfilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
